name: NumPy and MLflow versions

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: [ 'ubuntu-latest' ]

    steps:

      - name: Python virtual environment setup
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.19

      - name: install training requirments
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy==1.26.4
          python -m pip install mlflow --ignore-installed

      - name: Check the numpy version
        run: |
          python -m pip freeze | grep numpy
          python -c 'import numpy as np
          print(np.__version__)'
